services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    volumes:
      - django_static:/app/static
      - django_media:/app/media
    env_file:
      - ./backend/.env.prod
    networks:
      - og_network_prod

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    env_file:
      - ./frontend/.env.local
    networks:
      - og_network_prod

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/production.conf:/etc/nginx/conf.d/default.conf:z
      - django_static:/app/static:ro
      - django_media:/app/media:ro
      - ./docker/certbot/conf:/etc/letsencrypt:z
      - ./docker/certbot/www:/var/www/certbot:z
    depends_on:
      - backend
      - frontend
    networks:
      - og_network_prod

networks:
  og_network_prod:
    driver: bridge

volumes:
  django_static:
  django_media:
