# Generated by Django 4.2.30 on 2026-05-03 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_is_confirmed_by_client_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['category', 'order', 'name']},
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('HAIRCUT', 'Cortes de Cabello'), ('BEARD', 'Barba & Grooming'), ('PACKAGE', 'Paquetes & Combos'), ('OTHER', 'Otros Servicios')], default='HAIRCUT', max_length=20, verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='service',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Orden de visualización'),
        ),
    ]
