# Generated by Django 4.2.30 on 2026-05-03 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workphoto',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Contenido de Galería', 'verbose_name_plural': 'Contenidos de Galería'},
        ),
        migrations.AddField(
            model_name='workphoto',
            name='media_type',
            field=models.CharField(choices=[('IMAGE', 'Imagen'), ('VIDEO', 'Video')], default='IMAGE', max_length=10, verbose_name='Tipo de Media'),
        ),
        migrations.AddField(
            model_name='workphoto',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='gallery/videos/', verbose_name='Video (Solo si es tipo Video)'),
        ),
        migrations.AlterField(
            model_name='workphoto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/images/', verbose_name='Imagen (Solo si es tipo Imagen)'),
        ),
    ]
