# Generated by Django 4.2.30 on 2026-05-03 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_workphoto_options_workphoto_media_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workphoto',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='gallery/images/', verbose_name='Imagen (Soporta HEIC, JPG, PNG)'),
        ),
    ]
