upstream backend {
    server backend:8000;
}

upstream frontend {
    server frontend:3000;
}

server {
    listen 80;
    server_name ogbarberia.com www.ogbarberia.com;
    client_max_body_size 50M;

    # Archivos estáticos de Django
    location /static/ {
        alias /app/static/;
    }

    # Archivos de medios de Django
    location /media/ {
        alias /app/media/;
    }

    # API y Admin
    location ~ ^/(api|admin|silk) {
        proxy_pass http://backend;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

    # Frontend (Next.js)
    location / {
        proxy_pass http://frontend;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }
}
